apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-lnfl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-lnfl@sha256:b0c838f6e6709943fdcd361921b062e38fb8c3e446363f457fc6dc69e084ee97
        name: my-nodejs
        resources: {}
status: {}
